language: php

os: linux
dist: xenial

services:
  - mysql
  - postgresql

addons:
  firefox: "47.0.1"
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master
  allow_failures:
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE

before_install:
  - phpenv config-rm xdebug.ini

  - if [ -z $CHECK_GRUNT ]; then
    export CHECK_GRUNT=no;
    fi

  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - if [ "$MOODLE_VERSION" = 36 ] || [ "$MOODLE_VERSION" -le 34 ]; then NVMVERSION=8.9; else NVMVERSION=14.0.0; fi
  - nvm install $NVMVERSION;
  - nvm use $NVMVERSION;

  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd || true
  - moodle-plugin-ci phpmd || true
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt || [ "$CHECK_GRUNT" = 'no' ]
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
